site_name: Chivalry 2 Mini Maps
repo_url: https://github.com/Knutschbert/Chiv2MiniMaps
edit_uri: blob/main/docs/


theme:
    name: 'material'
    custom_dir: custom_dir/
    font:
      text: Volkov
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - nl2br
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  - admonition
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
    # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid    
  - toc:
      permalink: true

plugins:
  - mermaid2
  - search
  - roamlinks 
  - embed_file 
  - callouts

extra_css:
  - javascripts/mermaid-center.css
  - css/leaflet.css
  - css/qgis2web.css
  - css/fontawesome-all.min.css
  - chiv/chivmap.css
  - javascripts/extra.css
  - |
    body {
      padding-top: 60px; /* Adjust the top padding to make space for the new header */
    }
    .md-header-wrapper {
      display: none; /* Hide the original header */
    }
    .custom-header {
      position: fixed;
      top: 0;
      width: 100%;
      background-color: #37474F; /* Customize the background color */
      color: #FFFFFF; /* Customize the text color */
      padding: 10px 20px; /* Customize padding */
      z-index: 1000; /* Set a high z-index to ensure it's above other elements */
    }

extra_javascript:
  - javascripts/mathjax.js
  - js/qgis2web_expressions.js
  - js/leaflet.js
  - js/leaflet.rotatedMarker.js
  - js/leaflet.pattern.js
  - js/leaflet-hash.js
  - js/Autolinker.min.js
  - js/rbush.min.js
  - js/labelgun.min.js
  - js/labels.js
  - chiv/chivmap.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
